import Head from 'next/head';

export default function Login() {
  let inputStyle =
    'block p-2 mb-4 w-full text-sm text-gray-900 bg-white rounded-lg border focus:outline-none focus:shadow-outline py-3';
  return (
    <div className="flex justify-center items-center h-screen">
      <Head>
        <title>Login </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <form
        className="
         flex 
         flex-col
         shadow-md
         w-1/4
         h-96
         p-10
         border
         rounded-md
         "
      >
        <span className="mb-8 text-2xl">Sign In</span>
        <input type="text" placeholder="Email" className={inputStyle} />
        <input type="password" placeholder="Password" className={inputStyle} />
        <input type="submit" value="SIGN IN" className="bg-emerald-300 py-2 rounded" />
        <span className="mt-12 text-center">
          Dont have an account yet ? <a>Sign Up</a>
        </span>
      </form>
    </div>
  );
}
