import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../ui/components/Header';
export default function Home() {
  fetch('https://jsonplaceholder.typicode.com/todos/1')
    .then((response) => response.json())
    .then((json) => console.log(json));
  return (
    <div className={styles.container}>
      <Head>
        <title>FreindsClub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}
