import Head from 'next/head';
import React, { useEffect } from 'react';
import Header from '../ui/components/Header';
import styles from '../styles/Home.module.css';
import { load } from '../store/slices/userSlice';
import { useSelector, useDispatch } from 'react-redux';

function Home() {
  const dispatch = useDispatch();
  const user = useSelector((state) => state.user);

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/users')
      .then((response) => response.json())
      .then((result) => {
        dispatch(
          load(
            result.map((x) => ({
              id: x.id,
              name: x.name,
              username: x.username.toLowerCase(),
            })),
          ),
        );
      });
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>FreindsClub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}

export default Home;
